# Generated by Django 4.0.3 on 2022-03-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=5)),
                ('numero_documento', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_salida', models.DateField()),
            ],
        ),
    ]
